export const sinaisLibras = [
    { letra: "A", imagem: "/alfabeto/a.svg" },
    { letra: "B", imagem: "/alfabeto/b.svg" },
    { letra: "C", imagem: "/alfabeto/c.svg" },
    { letra: "D", imagem: "/alfabeto/d.svg" },
    { letra: "E", imagem: "/alfabeto/e.svg" },
    { letra: "F", imagem: "/alfabeto/f.svg" },
    { letra: "G", imagem: "/alfabeto/g.svg" },
    { letra: "H", imagem: "/alfabeto/h.svg" },
    { letra: "I", imagem: "/alfabeto/i.svg" },
    { letra: "J", imagem: "/alfabeto/j.svg" },
    { letra: "K", imagem: "/alfabeto/k.svg" },
    { letra: "L", imagem: "/alfabeto/l.svg" },
    { letra: "M", imagem: "/alfabeto/m.svg" },
    { letra: "N", imagem: "/alfabeto/n.svg" },
    { letra: "O", imagem: "/alfabeto/o.svg" },
    { letra: "P", imagem: "/alfabeto/p.svg" },
    { letra: "Q", imagem: "/alfabeto/q.svg" },
    { letra: "R", imagem: "/alfabeto/r.svg" },
    { letra: "S", imagem: "/alfabeto/s.svg" },
    { letra: "T", imagem: "/alfabeto/t.svg" },
    { letra: "U", imagem: "/alfabeto/u.svg" },
    { letra: "V", imagem: "/alfabeto/v.svg" },
    { letra: "W", imagem: "/alfabeto/w.svg" },
    { letra: "X", imagem: "/alfabeto/x.svg" },
    { letra: "Y", imagem: "/alfabeto/y.svg" },
    { letra: "Z", imagem: "/alfabeto/z.svg" },
];